CREATE TABLE userpost(
    postId VARCHAR(36) PRIMARY KEY,
    userId VARCHAR(28) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE usercomments(
    commentId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    postId VARCHAR(36) NOT NULL,
    userId VARCHAR(28) NOT NULL,
    comments TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (postId) REFERENCES userpost(postId) ON DELETE CASCADE
);
CREATE TABLE userlikes(
    likerId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    postId VARCHAR(36) NOT NULL,
    userId VARCHAR(28) NOT NULL,
    FOREIGN KEY (postId) REFERENCES userpost(postId) ON DELETE CASCADE
)