export interface DuelmastersCard {
  _id: string;
  cardName: string;
  detailUrl: string;
  urlimage: string;
  type: string;
  typeJP: string;
  civilization: string[]; 
  civilizationJP: string[];
  rarity: string;
  power: string;
  cost: string;
  mana: string;
  race: string[];
  raceJP: string[];
  illustrator: string;
  effects: string;
  effectsJP: string;
  cardUid: string;
  cardId:string;
  booster: string;
  type2: string;
  type2JP: string;
  civilization2: string[]; 
  civilization2JP: string[];
  power2: string;
  cost2: string;
  mana2: string;
  race2: string[];
  race2JP: string[];
  effects2: string;
  effects2JP: string;
  cardName2: string;
}
